In [137]:
import pandas as pd
import matplotlib

In [138]:
df_G = pd.read_csv("excel files\games.csv")
df_G.head()

,GameID,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio
0,201,Grand Theft Auto V,2013,Action,Tactical Shooter,Rockstar North
1,202,The Witcher 3: Wild Hunt,2015,Action,Action RPG,CD PROJEKT RED
2,203,Portal 2,2011,Shooter,Tactical Shooter,Valve Software
3,204,Counter-Strike: Global Offensive,2012,Shooter,Tactical Shooter,Valve Software
4,205,Portal,2007,Action,Tactical Shooter,Valve Software

In [139]:
df_R = pd.read_csv("excel files\steam_reviews.csv")
df_R.head()

,MetricID,GameID,Steam_AppID,Steam_Rating_Pct,Steam_Total_Reviews,RAWG_Rating,Added_Count,Ratings_Count,Fetched_At,Metacritics
0,181,699,251570,87.29,273867,3.36,4331,500,2026-10-01 19:53:18,NaN
1,182,405,752590,93.11,63615,4.14,7179,1546,2026-10-01 19:53:24,81.0
2,183,481,278360,92.68,12178,3.15,6168,644,2026-10-01 19:53:29,73.0
3,184,503,1222700,87.33,78379,4.13,5966,1635,2026-10-01 19:53:34,78.0
4,185,585,384190,93.07,22018,3.91,5172,1097,2026-10-01 19:53:40,83.0

In [140]:
df_P = pd.read_csv("excel files\steam_prices.csv")
df_P.head()

,PriceID,GameID,Steam_AppID,Initial_Price,Final_Price,Discount_Pct,Is_Free,Updated_At
0,509,699,251570,43.99,24.19,45,0,2026-10-01 20:28:56
1,510,405,752590,39.99,3.99,90,0,2026-10-01 20:28:56
2,511,481,278360,14.99,2.99,80,0,2026-10-01 20:28:57
3,512,503,1222700,29.99,8.99,70,0,2026-10-01 20:28:57
4,513,585,384190,19.99,4.99,75,0,2026-10-01 20:28:59

In [141]:
df = pd.merge(df_G, df_R, on="GameID", how="inner")
df.head()

,GameID,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,MetricID,Steam_AppID,Steam_Rating_Pct,Steam_Total_Reviews,RAWG_Rating,Added_Count,Ratings_Count,Fetched_At,Metacritics
0,201,Grand Theft Auto V,2013,Action,Tactical Shooter,Rockstar North,370,3240220,83.47,213584,4.47,22739,7445,2026-10-01 20:00:06,NaN
1,202,The Witcher 3: Wild Hunt,2015,Action,Action RPG,CD PROJEKT RED,607,292030,96.50,831426,NaN,0,0,2026-10-01 20:04:29,93.0
2,203,Portal 2,2011,Shooter,Tactical Shooter,Valve Software,496,620,98.72,390753,4.57,20976,6144,2026-10-01 20:02:14,95.0
3,205,Portal,2007,Action,Tactical Shooter,Valve Software,495,620,98.72,390753,4.48,17885,5056,2026-10-01 20:02:14,95.0
4,206,Tomb Raider,2013,Action,Action Stealth,Crystal Dynamics,618,391220,94.22,127540,4.06,17882,4116,2026-10-01 20:04:39,86.0

In [142]:
df = pd.merge(df, df_P, on="GameID", how="inner")
df.head()

,GameID,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,MetricID,Steam_AppID_x,Steam_Rating_Pct,Steam_Total_Reviews,...,Ratings_Count,Fetched_At,Metacritics,PriceID,Steam_AppID_y,Initial_Price,Final_Price,Discount_Pct,Is_Free,Updated_At
0,201,Grand Theft Auto V,2013,Action,Tactical Shooter,Rockstar North,370,3240220,83.47,213584,...,7445,2026-10-01 20:00:06,NaN,698,3240220,29.99,14.99,50,0,2026-10-01 20:31:32
1,202,The Witcher 3: Wild Hunt,2015,Action,Action RPG,CD PROJEKT RED,607,292030,96.50,831426,...,0,2026-10-01 20:04:29,93.0,934,292030,49.99,24.99,50,0,2026-10-01 20:34:40
2,203,Portal 2,2011,Shooter,Tactical Shooter,Valve Software,496,620,98.72,390753,...,6144,2026-10-01 20:02:14,95.0,823,620,9.75,1.95,80,0,2026-10-01 20:33:12
3,205,Portal,2007,Action,Tactical Shooter,Valve Software,495,620,98.72,390753,...,5056,2026-10-01 20:02:14,95.0,822,620,9.75,1.95,80,0,2026-10-01 20:33:12
4,206,Tomb Raider,2013,Action,Action Stealth,Crystal Dynamics,618,391220,94.22,127540,...,4116,2026-10-01 20:04:39,86.0,945,391220,29.99,4.49,85,0,2026-10-01 20:34:50

In [143]:
df = df.drop(columns=["GameID","MetricID","PriceID","Steam_AppID_x","Steam_AppID_y","Fetched_At","Updated_At"])
df

,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,Steam_Rating_Pct,Steam_Total_Reviews,RAWG_Rating,Added_Count,Ratings_Count,Metacritics,Initial_Price,Final_Price,Discount_Pct,Is_Free
0,Grand Theft Auto V,2013,Action,Tactical Shooter,Rockstar North,83.47,213584,4.47,22739,7445,NaN,29.99,14.99,50,0
1,The Witcher 3: Wild Hunt,2015,Action,Action RPG,CD PROJEKT RED,96.50,831426,NaN,0,0,93.0,49.99,24.99,50,0
2,Portal 2,2011,Shooter,Tactical Shooter,Valve Software,98.72,390753,4.57,20976,6144,95.0,9.75,1.95,80,0
3,Portal,2007,Action,Tactical Shooter,Valve Software,98.72,390753,4.48,17885,5056,95.0,9.75,1.95,80,0
4,Tomb Raider,2013,Action,Action Stealth,Crystal Dynamics,94.22,127540,4.06,17882,4116,86.0,29.99,4.49,85,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,7 Days to Die,2013,Shooter,Survival Horror,Telltale Games,87.29,273867,3.36,4331,500,NaN,43.99,24.19,45,0
518,7 Days to Die,2013,Shooter,Survival Horror,Telltale Games,87.29,273867,3.36,4331,500,NaN,43.99,24.19,45,0
519,7 Days to Die,2013,Shooter,Survival Horror,Telltale Games,87.29,273867,3.36,4331,500,NaN,43.99,24.19,45,0
520,7 Days to Die,2013,Shooter,Survival Horror,Telltale Games,87.29,273867,3.36,4331,500,NaN,43.99,24.19,45,0
521,Kerbal Space Program,2015,Action,Action Adventure,Squad,95.77,121011,4.16,4331,412,88.0,36.99,9.24,75,0

In [144]:
df = df.drop_duplicates(subset=["Game_Name"], keep="first")
print("Duplicate games count remaining:", df.duplicated(subset=["Game_Name"]).sum())

Duplicate games count remaining: 0

In [145]:
df = df.dropna(subset=['Steam_Rating_Pct']).reset_index(drop=True)

In [146]:
df[df["Initial_Price"].isnull()]

,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,Steam_Rating_Pct,Steam_Total_Reviews,RAWG_Rating,Added_Count,Ratings_Count,Metacritics,Initial_Price,Final_Price,Discount_Pct,Is_Free
38,Half-Life 2: Deathmatch,2004,Action,Tactical Shooter,Valve Software,90.16,10260,3.29,11258,908,NaN,NaN,NaN,0,0
52,Half-Life Deathmatch: Source,2006,Action,Tactical Shooter,Valve Software,74.51,4367,3.21,10390,727,NaN,NaN,NaN,0,0
91,ARK: Survival Of The Fittest,2016,Action,Tactical Shooter,Instinct Games,72.53,4623,2.60,8921,523,NaN,NaN,NaN,0,0
159,Ori and the Blind Forest,2015,Action,Metroidvania,Moon Studios,93.83,51100,4.37,7502,1540,88.0,NaN,NaN,0,0
163,Viscera Cleanup Detail: Shadow Warrior,2013,Action,Tactical Shooter,Unknown,80.96,2458,2.59,7414,577,NaN,NaN,NaN,0,0
204,Sleeping Dogs: Definitive Edition,2014,Action,Action Adventure,Feral Interactive,94.08,70640,4.15,6754,1192,NaN,NaN,NaN,0,0
226,Sniper Elite V2,2012,Action,Action Stealth,Rebellion,88.14,6275,3.40,6454,853,66.0,NaN,NaN,0,0
237,POSTAL 2,2003,Action,Tactical Shooter,Running With Scissors,96.98,117919,3.91,6351,1080,59.0,NaN,NaN,0,0
238,Forza Horizon 4,2018,Sports,Tactical Shooter,Playground Games,84.09,44,4.37,6344,1656,NaN,NaN,NaN,0,0
268,Half-Life: Source,2004,Action,Tactical Shooter,Valve Software,74.51,4367,3.71,5998,555,NaN,NaN,NaN,0,0
310,F.E.A.R.,2005,Action,Tactical Shooter,Monolith Productions,93.54,14036,4.27,5485,1046,88.0,NaN,NaN,0,0
329,Mark of the Ninja,2012,Action,Action Stealth,Klei Entertainment,96.87,11742,3.99,5310,769,91.0,NaN,NaN,0,0
350,Dying Light,2015,Action,Action Adventure,Techland,95.23,374064,4.14,7021,1113,87.0,NaN,NaN,0,0
385,Yakuza Kiwami,2016,Action,Action Adventure,Ryu ga Gotoku Studio,82.46,1374,4.10,4745,782,NaN,NaN,NaN,0,0
386,Marvel's Guardians of the Galaxy,2021,Action,Action Adventure,Eidos Montreal,75.00,16,4.29,4743,905,NaN,NaN,NaN,55,0

In [147]:
df["Metacritics"].isnull().sum()

np.int64(136)

In [148]:
import numpy as np

In [149]:
df["Metacritics"] = df["Metacritics"].fillna(df["Steam_Rating_Pct"])

In [150]:
bins = [-1, 19, 39, 69, 79, 94, 100]
labels = [
    "Overwhelmingly Negative",
    "Mostly Negative",
    "Mixed",
    "Mostly Positive",
    "Very Positive",
    "Overwhelmingly Positive",
]

df["steam_rating_text"] = pd.cut(
    df["Steam_Rating_Pct"], bins=bins, labels=labels
)
df = df.drop(columns=["Steam_Rating_Pct"])

In [151]:
df.head()

,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,Steam_Total_Reviews,RAWG_Rating,Added_Count,Ratings_Count,Metacritics,Initial_Price,Final_Price,Discount_Pct,Is_Free,steam_rating_text
0,Grand Theft Auto V,2013,Action,Tactical Shooter,Rockstar North,213584,4.47,22739,7445,83.47,29.99,14.99,50,0,Very Positive
1,The Witcher 3: Wild Hunt,2015,Action,Action RPG,CD PROJEKT RED,831426,NaN,0,0,93.00,49.99,24.99,50,0,Overwhelmingly Positive
2,Portal 2,2011,Shooter,Tactical Shooter,Valve Software,390753,4.57,20976,6144,95.00,9.75,1.95,80,0,Overwhelmingly Positive
3,Portal,2007,Action,Tactical Shooter,Valve Software,390753,4.48,17885,5056,95.00,9.75,1.95,80,0,Overwhelmingly Positive
4,Tomb Raider,2013,Action,Action Stealth,Crystal Dynamics,127540,4.06,17882,4116,86.00,29.99,4.49,85,0,Overwhelmingly Positive

In [152]:
df[
    df["steam_rating_text"].isin(
        ["Overwhelmingly Negative"]
    )
]

,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,Steam_Total_Reviews,RAWG_Rating,Added_Count,Ratings_Count,Metacritics,Initial_Price,Final_Price,Discount_Pct,Is_Free,steam_rating_text
254,Tom Clancy's The Division,2016,Action,Tactical Shooter,Ubisoft,6,3.7,6143,1351,16.67,49.99,49.99,0,0,Overwhelmingly Negative