In [44]:
import pandas as pd
import matplotlib

In [45]:
df_G = pd.read_csv("excel files\games.csv")
df_G.head()

,GameID,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio
0,1,Grand Theft Auto V,2013,Action,Tactical Shooter,Rockstar North
1,2,The Witcher 3: Wild Hunt,2015,Action,Action RPG,CD PROJEKT RED
2,3,Portal 2,2011,Shooter,Tactical Shooter,Valve Software
3,4,Counter-Strike: Global Offensive,2012,Shooter,Tactical Shooter,Valve Software
4,5,Portal,2007,Action,Tactical Shooter,Valve Software

In [46]:
df_R = pd.read_csv("excel files\steam_reviews.csv")
df_R.head()

,MetricID,GameID,Steam_AppID,Steam_Rating_Pct,Steam_Total_Reviews,RAWG_Rating,Added_Count,Ratings_Count,Fetched_At
0,1,59,108710,89.55,45887,4.09,10539,2301,2026-09-29 17:10:21
1,2,146,214490,92.88,48643,4.21,8230,1476,2026-09-29 17:10:25
2,3,183,239200,69.09,7254,3.23,7496,686,2026-09-29 17:10:28
3,4,63,57300,95.47,20455,3.65,10448,1241,2026-09-29 17:10:36
4,5,158,945360,92.33,659694,3.83,7982,1350,2026-09-29 17:10:39

In [47]:
df_P = pd.read_csv("excel files\steam_prices.csv")
df_P.head()

,PriceID,GameID,Steam_AppID,Initial_Price,Final_Price,Discount_Pct,Is_Free,Currency,Updated_At
0,1,59,108710,12.99,12.99,0,0,EUR,2026-09-29 17:20:37
1,2,146,214490,39.99,39.99,0,0,EUR,2026-09-29 17:20:39
2,3,183,239200,19.50,19.50,0,0,EUR,2026-09-29 17:20:41
3,4,63,57300,19.50,19.50,0,0,EUR,2026-09-29 17:20:42
4,5,158,945360,4.49,4.49,0,0,EUR,2026-09-29 17:20:44

In [48]:
df_P = df_P.drop(columns="Currency")
df_P.head()

,PriceID,GameID,Steam_AppID,Initial_Price,Final_Price,Discount_Pct,Is_Free,Updated_At
0,1,59,108710,12.99,12.99,0,0,2026-09-29 17:20:37
1,2,146,214490,39.99,39.99,0,0,2026-09-29 17:20:39
2,3,183,239200,19.50,19.50,0,0,2026-09-29 17:20:41
3,4,63,57300,19.50,19.50,0,0,2026-09-29 17:20:42
4,5,158,945360,4.49,4.49,0,0,2026-09-29 17:20:44

In [50]:
df = pd.merge(df_G, df_R, on="GameID", how="inner")
df.head()

,GameID,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,MetricID,Steam_AppID,Steam_Rating_Pct,Steam_Total_Reviews,RAWG_Rating,Added_Count,Ratings_Count,Fetched_At
0,1,Grand Theft Auto V,2013,Action,Tactical Shooter,Rockstar North,66,3240220,83.46,213144,4.47,22737,7446,2026-09-29 17:14:12
1,2,The Witcher 3: Wild Hunt,2015,Action,Action RPG,CD PROJEKT RED,158,292030,96.70,826817,4.64,22371,7283,2026-09-29 17:19:03
2,3,Portal 2,2011,Shooter,Tactical Shooter,Valve Software,128,620,98.72,390702,4.57,20975,6144,2026-09-29 17:17:24
3,5,Portal,2007,Action,Tactical Shooter,Valve Software,127,620,98.72,390702,4.48,17885,5056,2026-09-29 17:17:21
4,6,Tomb Raider,2013,Action,Action Stealth,Crystal Dynamics,165,391220,94.23,127501,4.06,17881,4116,2026-09-29 17:19:27

In [51]:
df = pd.merge(df, df_P, on="GameID", how="inner")
df.head()

,GameID,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,MetricID,Steam_AppID_x,Steam_Rating_Pct,Steam_Total_Reviews,...,Added_Count,Ratings_Count,Fetched_At,PriceID,Steam_AppID_y,Initial_Price,Final_Price,Discount_Pct,Is_Free,Updated_At
0,1,Grand Theft Auto V,2013,Action,Tactical Shooter,Rockstar North,66,3240220,83.46,213144,...,22737,7446,2026-09-29 17:14:12,64,3240220,29.99,29.99,0,0,2026-09-29 17:22:21
1,2,The Witcher 3: Wild Hunt,2015,Action,Action RPG,CD PROJEKT RED,158,292030,96.70,826817,...,22371,7283,2026-09-29 17:19:03,153,292030,49.99,24.99,50,0,2026-09-29 17:24:49
2,3,Portal 2,2011,Shooter,Tactical Shooter,Valve Software,128,620,98.72,390702,...,20975,6144,2026-09-29 17:17:24,123,620,9.75,9.75,0,0,2026-09-29 17:24:00
3,5,Portal,2007,Action,Tactical Shooter,Valve Software,127,620,98.72,390702,...,17885,5056,2026-09-29 17:17:21,122,620,9.75,9.75,0,0,2026-09-29 17:23:58
4,6,Tomb Raider,2013,Action,Action Stealth,Crystal Dynamics,165,391220,94.23,127501,...,17881,4116,2026-09-29 17:19:27,160,391220,29.99,29.99,0,0,2026-09-29 17:25:01

In [52]:
df = df.drop(columns=["GameID","MetricID","PriceID","Steam_AppID_x","Steam_AppID_y","Fetched_At","Updated_At"])
df

,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,Steam_Rating_Pct,Steam_Total_Reviews,RAWG_Rating,Added_Count,Ratings_Count,Initial_Price,Final_Price,Discount_Pct,Is_Free
0,Grand Theft Auto V,2013,Action,Tactical Shooter,Rockstar North,83.46,213144,4.47,22737,7446,29.99,29.99,0,0
1,The Witcher 3: Wild Hunt,2015,Action,Action RPG,CD PROJEKT RED,96.70,826817,4.64,22371,7283,49.99,24.99,50,0
2,Portal 2,2011,Shooter,Tactical Shooter,Valve Software,98.72,390702,4.57,20975,6144,9.75,9.75,0,0
3,Portal,2007,Action,Tactical Shooter,Valve Software,98.72,390702,4.48,17885,5056,9.75,9.75,0,0
4,Tomb Raider,2013,Action,Action Stealth,Crystal Dynamics,94.23,127501,4.06,17881,4116,29.99,29.99,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,"Papers, Please",2013,Platformer,3D Platformer,Lucas Pope,97.37,73487,4.37,7291,1786,9.75,9.75,0,0
170,Call of Duty: Black Ops 3,2015,Action,Tactical Shooter,Raven Software,88.54,158145,3.27,7286,1511,59.99,59.99,0,0
171,Killing Floor,2009,Action,Tactical Shooter,Tripwire Interactive,46.81,16526,3.45,7271,856,39.99,39.99,0,0
172,Divinity: Original Sin 2,2017,RPG,Action RPG,Larian Studios,95.54,180998,4.38,7270,1690,44.99,44.99,0,0
173,Shadowrun Returns,2013,RPG,Tactical Shooter,Harebrained Schemes,88.23,9555,3.50,7268,732,14.99,14.99,0,0

In [54]:
print("Duplicate games count:", df.duplicated(subset=["Game_Name"]).sum())
print(df[df.duplicated(subset=["Game_Name"], keep=False)])

Duplicate games count: 0
Empty DataFrame
Columns: [Game_Name, Game_Year, Game_Genre, Game_Subgenre, Game_Studio, Steam_Rating_Pct, Steam_Total_Reviews, RAWG_Rating, Added_Count, Ratings_Count, Initial_Price, Final_Price, Discount_Pct, Is_Free]
Index: []

In [64]:
df = df.dropna(subset=['Steam_Rating_Pct']).reset_index(drop=True)

In [65]:
# Show all rows that have at least one null value in any column
df[df.isnull().any(axis=1)]

,Game_Name,Game_Year,Game_Genre,Game_Subgenre,Game_Studio,Steam_Rating_Pct,Steam_Total_Reviews,RAWG_Rating,Added_Count,Ratings_Count,Initial_Price,Final_Price,Discount_Pct,Is_Free
29,The Witcher 2: Assassins of Kings Enhanced Edi...,2012,RPG,Action RPG,CD PROJEKT RED,89.75,80957,4.17,12059,2185,NaN,NaN,85,0
37,Half-Life 2: Deathmatch,2004,Action,Tactical Shooter,Valve Software,90.16,10259,3.29,11258,908,NaN,NaN,0,0
44,Deus Ex: Mankind Divided,2016,Action,Tactical Shooter,Eidos Montreal,77.26,30736,3.96,10825,2022,NaN,NaN,90,0
51,Half-Life Deathmatch: Source,2006,Action,Tactical Shooter,Valve Software,74.50,4369,3.21,10390,727,NaN,NaN,0,0
70,For Honor,2017,Action,Action Adventure,Ubisoft,69.08,108930,3.30,9700,1684,NaN,NaN,90,0
90,ARK: Survival Of The Fittest,2016,Action,Tactical Shooter,Instinct Games,72.53,4623,2.60,8921,523,NaN,NaN,0,0
110,Watch Dogs,2014,Action,Action Stealth,Ubisoft,82.00,96473,3.60,8467,2231,NaN,NaN,95,0
115,Metro Exodus,2019,Action,Tactical Shooter,4A Games,90.01,117678,4.17,8432,1717,NaN,NaN,90,0
155,Ori and the Blind Forest,2015,Action,Metroidvania,Moon Studios,93.83,51089,4.37,7501,1540,NaN,NaN,0,0
159,Viscera Cleanup Detail: Shadow Warrior,2013,Action,Tactical Shooter,Devolver Digital,80.95,2457,2.59,7414,577,NaN,NaN,0,0
160,Watch Dogs 2,2016,Action,Action Stealth,Ubisoft Montreal,82.00,96473,3.84,7410,1782,NaN,NaN,95,0
161,Thief,2014,Action,Tactical Shooter,Feral Interactive,88.28,37406,3.26,7383,1284,NaN,NaN,91,0